name: Publish

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: maximousblk/setup-deno@v2

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: deno install
      - run: deno task lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: maximousblk/setup-deno@v2

      - run: deno install
      - run: deno task test

  publish:
    runs-on: ubuntu-latest
    needs: [lint, test]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish