name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: maximousblk/setup-deno@v2

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: deno install
      - run: deno task lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: maximousblk/setup-deno@v2

      - run: deno install
      - run: deno task test
      - run: deno task test:publish